### PR TITLE
adding type using (sub-)headers instead of bullet lists

### PR DESCRIPTION
**Pull request by jcolomb**
I gave it a try, and succeeded :) not sure it is the best way to code this though ??

add a way to export as headings, default behavior not changed.
NB: may need a message if type given wrongly.

NB2: the default does order sublist elements but not first level elements, I did not change that, but may not be what people want (?). Also the ordered list way gets stange sublisting due to that.

### CODE REVIEW

**Comment by jcolomb** [comment]
It works now, but has no test for the new output type.

**Comment by debruine** [comment]
Thanks! I'm going to re-write a little bit of the code to use match.arg. Sorry this took so long for me to deal with!

**Comment by debruine** [comment]
Sorry, I tried writing tests for it, everything ended up mangled, and I had to revert it to the original. Can you just describe what you want it to do? I was getting lists that looked like:

```
# 1_no_title

A

# 2_no_title

B
```

or 

```
# countries

## Netherlands

## Germany

# cities

## Glasgow

## Berlin
```

I can't imagine that being useful to anyone. So I assume you have a use case that makes sense?

**Comment by jcolomb** [comment]
long time ago, but I think the idea was:

# level 1

## level2

### level 3

my use case was to collect data in yaml but render it in a nice pdf using headers (because there are a lot of level 1).

**Comment by jcolomb** [comment]
Hello, 
3 years later, I was trying to use this and realise there have been some issues and this function was reset to the old one... was it accidental ?

**Pull request merged**
